api: '1.20.4'
name: ExtraEnchants
version: '1.0'
main: com.github.yuqingliu.extraenchants.Main
api-version: '1.13'
commands:
  wand:
    description: Mark blocks/entities which can view GUI, left-click to mark, right-click to unmark
    usage: /wand etable; /wand anvil; /wand grindstone
    permission: extraenchants.admin
  enchant:
    description: Enchant main hand item
    usage: /enchant <EnchantID> <Level>
    permission: extraenchants.admin
  level:
    description: Set an enchantment's maximum level
    usage: /level set <EnchantID> <Level>
    permission: extraenchants.admin
  list:
    description: List all available enchantemnts
    usage: /list
    permission: extraenchants.admin

permissions:
  extraenchants.admin:
    description: Allows use admin commands
    default: op
  extraenchants.user:
    description: Allows use regular commands
    default: true
