api: '1.20.4'
name: ExtraEnchants
version: '1.0'
main: com.github.yuqingliu.extraenchants.ExtraEnchantsImpl
api-version: '1.13'
commands:
  ee:
    description: Apply custom enchantments
    usage: /ee <Enchantment> <Level>
    aliases: [extraenchants]
    permission: extraenchants.ee
    permission-message: You do not have permission to use this command.
  eelist:
    description: List custom enchantments
    usage: /eelist
    aliases: [extraenchantslist]
    permission: extraenchants.eelist
    permission-message: You do not have permission to use this command.
  eeget:
    description: Gets a custom block that will open a custom menu
    usage: /eeget <menu>
    aliases: [extraenchantslist]
    permission: extraenchants.eeget
    permission-message: You do not have permission to use this command.

permissions:
  extraenchants.ee:
    description: Allows use of /ee
    default: op
  extraenchants.eelist:
    description: Allows use of /eelist
    default: op
  extraenchants.eeget:
    description: Allows use of /eeget
    default: op

